-- Не забывайте обновлять аналог всех enum`ов в панораме

local DOTA_DERIVED_STATS_CUSTOM_ENUM = {
    DOTA_ATTRIBUTE_STRENGTH_MAGIC_RESISTANCE = 80,
    DOTA_ATTRIBUTE_AGILITY_MOVE_SPEED = 81,
    DOTA_ATTRIBUTE_AGILITY_MOVE_SPEED_MAX = 82,
    DOTA_ATTRIBUTE_INTELLIGENCE_SPELL_AMP = 83
}

local TALENT_TREE_BRANCHES = {
    TALENT_TREE_RIGHT_BRANCH_25  = 1,
    TALENT_TREE_LEFT_BRANCH_25  = 2,
    TALENT_TREE_RIGHT_BRANCH_50 = 3,
    TALENT_TREE_LEFT_BRANCH_50 = 4,
    TALENT_TREE_RIGHT_BRANCH_75  = 5,
    TALENT_TREE_LEFT_BRANCH_75 = 6,
    TALENT_TREE_RIGHT_BRANCH_100 = 7,
    TALENT_TREE_LEFT_BRANCH_100 = 8,
    TALENT_TREE_BOTTOM_BRANCH_ATTRIBUTES = 9
}

local GAME_DIFFICULTIES = {
    GAME_DIFFICULTY_EASY = 1,
    GAME_DIFFICULTY_NORMAL = 2,
    GAME_DIFFICULTY_HARD = 3,
    GAME_DIFFICULTY_IMPOSSIBLE = 4
}

local CUSTOM_MODIFIER_PROPERTIES = {
    ["MODIFIER_PROPERTY_MOUNTAIN_STATS_STRENGTH_BONUS_PERCENTAGE"] = 8000,
    ["MODIFIER_PROPERTY_MOUNTAIN_STATS_AGILITY_BONUS_PERCENTAGE"] = 8001,
    ["MODIFIER_PROPERTY_MOUNTAIN_STATS_INTELLECT_BONUS_PERCENTAGE"] = 8002,
    ["MODIFIER_PROPERTY_MOUNTAIN_PHYSICAL_ARMOR_TOTAL_PERCENTAGE"] = 8003,
    ["MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_CONSTANT"] = 8004,
    ["MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_BONUS_CONSTANT"] = 8005,
    ["MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_BONUS_PERCENTAGE"] = 8006,
    ["MODIFIER_PROPERTY_MOUNTAIN_PRE_SPELL_CRITICAL_STRIKE"] = 8007,
    ["MODIFIER_PROPERTY_MOUNTAIN_LIFESTEAL"] = 8008,
    ["MODIFIER_PROPERTY_MOUNTAIN_SPELL_LIFESTEAL"] = 8009
}

for k,v in pairs(CUSTOM_MODIFIER_PROPERTIES) do
    _G[k] = v
end

_G.CUSTOM_MODIFIER_PROPERTIES_GETTERS = {
    MODIFIER_PROPERTY_MOUNTAIN_STATS_STRENGTH_BONUS_PERCENTAGE = "GetModifierBonusStats_Strength_Percentage",
    MODIFIER_PROPERTY_MOUNTAIN_STATS_AGILITY_BONUS_PERCENTAGE = "GetModifierBonusStats_Agility_Percentage",
    MODIFIER_PROPERTY_MOUNTAIN_STATS_INTELLECT_BONUS_PERCENTAGE = "GetModifierBonusStats_Intellect_Percentage",
    MODIFIER_PROPERTY_MOUNTAIN_PHYSICAL_ARMOR_TOTAL_PERCENTAGE = "GetModifierPhysicalArmorTotal_Percentage",
    MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_CONSTANT = "GetModifierBaseAttackTimeConstant",
    MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_BONUS_CONSTANT = "GetModifierBonusBaseAttackTimeConstant",
    MODIFIER_PROPERTY_MOUNTAIN_BASE_ATTACK_TIME_BONUS_PERCENTAGE = "GetModifierBonusBaseAttackTimePercentage",
    MODIFIER_PROPERTY_MOUNTAIN_PRE_SPELL_CRITICAL_STRIKE = "GetModifierPreSpell_CriticalStrike",
    MODIFIER_PROPERTY_MOUNTAIN_LIFESTEAL = "GetModifierLifesteal",
    MODIFIER_PROPERTY_MOUNTAIN_SPELL_LIFESTEAL = "GetModifierSpellLifesteal"
}

local UNIT_TESTS_LOG_LEVELS = {
    UNIT_TEST_LOG_LEVEL_INFO = 0,
    UNIT_TEST_LOG_LEVEL_ERROR = 1,
    UNIT_TEST_LOG_LEVEL_SUCCESS = 2
}

for k,v in pairs(UNIT_TESTS_LOG_LEVELS) do
    _G[k] = v
end

for k,v in pairs(GAME_DIFFICULTIES) do
    _G[k] = v
end

for k,v in pairs(DOTA_DERIVED_STATS_CUSTOM_ENUM) do
    _G[k] = v
end

for k,v in pairs(TALENT_TREE_BRANCHES) do
    _G[k] = v
end