/* eslint-disable no-undef */
"use strict";

var Constants = {};

Constants.TOP_BAR_BUTTONS = {
    DASHBOARD: 0,
    SETTINGS: 1,
    SCOREBOARD: 2,
    DISCORD: 3,
    DEBUG: 4,
    DONATE: 5,
    PLAYERS_TOP: 6
};

Constants.AttributeDerivedStats = {
    DOTA_ATTRIBUTE_STRENGTH_DAMAGE: 0,
    DOTA_ATTRIBUTE_STRENGTH_HP: 1,
    DOTA_ATTRIBUTE_STRENGTH_HP_REGEN: 2,
    DOTA_ATTRIBUTE_STRENGTH_MAGIC_RESISTANCE: 80,
    DOTA_ATTRIBUTE_AGILITY_DAMAGE: 3,
    DOTA_ATTRIBUTE_AGILITY_ARMOR: 4,
    DOTA_ATTRIBUTE_AGILITY_ATTACK_SPEED: 5,
    DOTA_ATTRIBUTE_AGILITY_MOVE_SPEED: 81,
    DOTA_ATTRIBUTE_AGILITY_MOVE_SPEED_MAX: 82,
    DOTA_ATTRIBUTE_INTELLIGENCE_DAMAGE: 6,
    DOTA_ATTRIBUTE_INTELLIGENCE_MANA: 7,
    DOTA_ATTRIBUTE_INTELLIGENCE_MANA_REGEN: 8,
    DOTA_ATTRIBUTE_INTELLIGENCE_SPELL_AMP: 83
};

Constants.TALENT_TREE_BRANCHES = {
    RIGHT_BRANCH_25: 1,
    LEFT_BRANCH_25: 2,
    RIGHT_BRANCH_50: 3,
    LEFT_BRANCH_50: 4,
    RIGHT_BRANCH_75: 5,
    LEFT_BRANCH_75: 6,
    RIGHT_BRANCH_100: 7,
    LEFT_BRANCH_100: 8,
    BOTTOM_BRANCH_ATTRIBUTES: 9
};

Constants.GAME_DIFFICULTY = {
    GAME_DIFFICULTY_EASY: 1,
    GAME_DIFFICULTY_NORMAL: 2,
    GAME_DIFFICULTY_HARD: 3,
    GAME_DIFFICULTY_IMPOSSIBLE: 4
};

Constants.UNIT_TESTS_LOG_LEVELS = {
    INFO: 0,
    ERROR: 1,
    SUCCESS: 2
};

GameUI.CustomUIConfig().Constants = Constants;
