declare const enum CustomEvent {
    CUSTOM_EVENT_ON_PRE_PLAYER_HERO_CHANGED = 1,
    CUSTOM_EVENT_ON_PLAYER_HERO_CHANGED = 2,
    CUSTOM_EVENT_ON_MODIFIER_DESTROYED = 3,
    CUSTOM_EVENT_ON_MODIFIER_ADDED = 4,
    CUSTOM_EVENT_ON_MODIFIER_REFRESHED = 5,
    CUSTOM_EVENT_ON_MODIFIER_STACKS_COUNT_CHANGED = 6,
    CUSTOM_EVENT_ON_RELOAD_KV = 7,
    CUSTOM_EVENT_ON_ADDON_PRECACHE = 8,
    CUSTOM_EVENT_ON_PRE_TAKE_DAMAGE = 9,
    CUSTOM_EVENT_ON_PRE_PLAYER_GAIN_GOLD = 10,
    CUSTOM_EVENT_ON_PLAYER_SELECTED_UNIT = 11,
    CUSTOM_EVENT_ON_ORDER = 12,
    CUSTOM_EVENT_ON_PLAYER_TEAM_SELECTED = 13,
    CUSTOM_EVENT_ON_PLAYER_HERO_SELECTED = 14,
    CUSTOM_EVENT_ON_PLAYER_MAP_SELECTED = 15
}

declare interface CustomEvents {
    RegisterEventHandler(eventType: CustomEvent, callback: (this: void, eventData: object) => void): void;
    RunEventByName(eventType: CustomEvent, data: object): void;
}

declare let CustomEvents: CustomEvents;
